[package]
name = "regtest2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notatin = { git = "https://github.com/strozfriedberg/notatin" }
#ascii_converter = "0.3.0"